# define the default serial port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB0

# this board uses openocd with the BlueProg adapter
FLASHER ?= openocd
PROGRAMMER ?= openocd

# openocd programmer is supported
PROGRAMMERS_SUPPORTED += openocd

FFLAGS += -f $(BOARDDIR)/blueprog.cfg
FFLAGS += -f $(BOARDDIR)/k1921vg015.cfg
FFLAGS += -c 'program $(ELFFILE) verify reset exit'
