#PROGRAMMER ?= toolchain/openocd-rus-mcu-win/bin/openocd
# FLASHDEPS = toolchain/openocd-rus-mcu-win/bin/openocd -f ./interface/blueprog.cfg ./target/k1921vg015.cfg -c 'program build/vgo15-fw.bin reset exit 0x80000000 verify'

#FLASHER ?= $(BOARDDIR)/toolchain/openocd-rus-mcu-win/bin/openocd.exe #под убунту

FFLAGS = -f $(BOARDDIR)/blueprog.cfg -f $(BOARDDIR)/k1921vg015.cfg -c 'program $(BINDIR)/vgo15-fw.bin reset exit 0x80000000 verify'
#FFLAGS = -f "D:/VUZD/ApparatnoeObespechenieIOT/RIOT/boards/bluebirdVG015/blueprog.cfg" \
        -f "D:/VUZD/ApparatnoeObespechenieIOT/RIOT/boards/bluebirdVG015/k1921vg015.cfg" \
        -c "program D:/VUZD/ApparatnoeObespechenieIOT/RIOT/examples-miem/hello-world/bin/bluebirdVG015/vgo15-fw.bin reset exit 0x80000000 verify"

FLASHFILE ?= $(BINFILE)

# Определяем адреса памяти для K1921VG015
ROM_START_ADDR ?= 0x80000000
ROM_LEN ?= 1024K
RAM_START_ADDR ?= 0x40000000
RAM_LEN ?= 256K

# Подключаем общий код для RISC-V
#include $(RIOTCPU)/riscv_common/Makefile.include
#include $(RIOTBOARD)/common/k1921vg015/Makefile.include

PROGRAMMER      ?= openocd
PROGRAMMERS_SUPPORTED += openocd

FLASHER         ?= openocd
FFLAGS          = -f $(BOARDDIR)/blueprog.cfg \
                  -f $(BOARDDIR)/k1921vg015.cfg \
                  -c 'program $(ELFFILE) verify reset exit'
