USEMODULE += periph

FEATURES_REQUIRED += periph_clic

ifneq (,$(filter periph_pm,$(USEMODULE)))
  FEATURES_REQUIRED += periph_wdt
endif

ifneq (,$(filter periph_timer,$(USEMODULE)))
  FEATURES_REQUIRED += periph_coretimer
endif

include $(RIOTCPU)/riscv_common/Makefile.dep
